#!/usr/bin/env python3

import os
from PyQt5 import QtWidgets
from traxis.gui import maingui


class TraxisApplicationWindow(QtWidgets.QMainWindow):

    """Simple wrapper class that creates a window to display GUI."""

    def __init__(self):
        super().__init__()

        self.setWindowTitle("Traxis")

        self.ui = maingui.MainGui(self)


# Main block that executes the application
if __name__ == '__main__':

    import sys
    import ctypes

    # if running on Windows, create an application user model id for this app
    # so that a custom taskbar icon can be used
    if hasattr(ctypes, 'windll'):
        appId = 'traxis.0.2.0'
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelId(appId)

    base = os.path.dirname(os.path.realpath(__file__))
    sys.path.insert(0, base)

    app = QtWidgets.QApplication(sys.argv)
    window = TraxisApplicationWindow()

    window.show()
    sys.exit(app.exec_())
