# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skeleton.ui'
#
# Created: Thu Nov  6 13:28:11 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_skeleton(object):
    def setupUi(self, skeleton):
        skeleton.setObjectName("skeleton")
        skeleton.resize(1070, 695)
        skeleton.setMaximumSize(QtCore.QSize(100000, 1000000))
        self.centralWidget = QtWidgets.QWidget(skeleton)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.TopBtnLayout = QtWidgets.QHBoxLayout()
        self.TopBtnLayout.setSpacing(10)
        self.TopBtnLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.TopBtnLayout.setContentsMargins(1, 1, 1, 1)
        self.TopBtnLayout.setObjectName("TopBtnLayout")
        self.vLine_div2 = QtWidgets.QFrame(self.centralWidget)
        self.vLine_div2.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.vLine_div2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vLine_div2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vLine_div2.setObjectName("vLine_div2")
        self.TopBtnLayout.addWidget(self.vLine_div2)
        self.verticalLayout_pointLabe = QtWidgets.QVBoxLayout()
        self.verticalLayout_pointLabe.setObjectName("verticalLayout_pointLabe")
        self.label_points = QtWidgets.QLabel(self.centralWidget)
        self.label_points.setObjectName("label_points")
        self.verticalLayout_pointLabe.addWidget(self.label_points)
        self.listWidget_points = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget_points.setObjectName("listWidget_points")
        self.verticalLayout_pointLabe.addWidget(self.listWidget_points)
        self.TopBtnLayout.addLayout(self.verticalLayout_pointLabe)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.TopBtnLayout.addWidget(self.line_4)
        self.tech_calc_btnLayoy = QtWidgets.QVBoxLayout()
        self.tech_calc_btnLayoy.setObjectName("tech_calc_btnLayoy")
        self.label_tech = QtWidgets.QLabel(self.centralWidget)
        self.label_tech.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_tech.setObjectName("label_tech")
        self.tech_calc_btnLayoy.addWidget(self.label_tech)
        self.btn_reset = QtWidgets.QPushButton(self.centralWidget)
        self.btn_reset.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_reset.setObjectName("btn_reset")
        self.tech_calc_btnLayoy.addWidget(self.btn_reset)
        self.label_Zoom = QtWidgets.QLabel(self.centralWidget)
        self.label_Zoom.setObjectName("label_Zoom")
        self.tech_calc_btnLayoy.addWidget(self.label_Zoom)
        self.horizontalLayout_Zoom = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Zoom.setObjectName("horizontalLayout_Zoom")
        self.btn_ZoomIn = QtWidgets.QPushButton(self.centralWidget)
        self.btn_ZoomIn.setObjectName("btn_ZoomIn")
        self.horizontalLayout_Zoom.addWidget(self.btn_ZoomIn)
        self.btn_ZoomOut = QtWidgets.QPushButton(self.centralWidget)
        self.btn_ZoomOut.setObjectName("btn_ZoomOut")
        self.horizontalLayout_Zoom.addWidget(self.btn_ZoomOut)
        self.tech_calc_btnLayoy.addLayout(self.horizontalLayout_Zoom)
        self.label_calc = QtWidgets.QLabel(self.centralWidget)
        self.label_calc.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_calc.setObjectName("label_calc")
        self.tech_calc_btnLayoy.addWidget(self.label_calc)
        self.btn_trackMom = QtWidgets.QPushButton(self.centralWidget)
        self.btn_trackMom.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_trackMom.setObjectName("btn_trackMom")
        self.tech_calc_btnLayoy.addWidget(self.btn_trackMom)
        self.btn_optDen = QtWidgets.QPushButton(self.centralWidget)
        self.btn_optDen.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_optDen.setObjectName("btn_optDen")
        self.tech_calc_btnLayoy.addWidget(self.btn_optDen)
        self.btn_angle = QtWidgets.QPushButton(self.centralWidget)
        self.btn_angle.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_angle.setStyleSheet("")
        self.btn_angle.setObjectName("btn_angle")
        self.tech_calc_btnLayoy.addWidget(self.btn_angle)
        spacerItem = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.tech_calc_btnLayoy.addItem(spacerItem)
        self.TopBtnLayout.addLayout(self.tech_calc_btnLayoy)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.TopBtnLayout.addWidget(self.line_2)
        self.usrSel_layout = QtWidgets.QVBoxLayout()
        self.usrSel_layout.setObjectName("usrSel_layout")
        self.label_userSle = QtWidgets.QLabel(self.centralWidget)
        self.label_userSle.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_userSle.setObjectName("label_userSle")
        self.usrSel_layout.addWidget(self.label_userSle)
        self.btn_openImage = QtWidgets.QPushButton(self.centralWidget)
        self.btn_openImage.setObjectName("btn_openImage")
        self.usrSel_layout.addWidget(self.btn_openImage)
        self.btn_placeMar = QtWidgets.QPushButton(self.centralWidget)
        self.btn_placeMar.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_placeMar.setObjectName("btn_placeMar")
        self.usrSel_layout.addWidget(self.btn_placeMar)
        self.dlForm = QtWidgets.QFormLayout()
        self.dlForm.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dlForm.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dlForm.setObjectName("dlForm")
        self.setDlLabel = QtWidgets.QLabel(self.centralWidget)
        self.setDlLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setDlLabel.setObjectName("setDlLabel")
        self.dlForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.setDlLabel)
        self.setDlLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.setDlLineEdit.setObjectName("setDlLineEdit")
        self.dlForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.setDlLineEdit)
        self.usrSel_layout.addLayout(self.dlForm)
        self.btn_drwAngle = QtWidgets.QPushButton(self.centralWidget)
        self.btn_drwAngle.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_drwAngle.setObjectName("btn_drwAngle")
        self.usrSel_layout.addWidget(self.btn_drwAngle)
        spacerItem1 = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.usrSel_layout.addItem(spacerItem1)
        self.TopBtnLayout.addLayout(self.usrSel_layout)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.TopBtnLayout.addWidget(self.line_3)
        self.ConsoleLayout = QtWidgets.QVBoxLayout()
        self.ConsoleLayout.setObjectName("ConsoleLayout")
        self.label_console = QtWidgets.QLabel(self.centralWidget)
        self.label_console.setObjectName("label_console")
        self.ConsoleLayout.addWidget(self.label_console)
        self.textBrowser_consoleOutput = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_consoleOutput.setMinimumSize(QtCore.QSize(250, 0))
        self.textBrowser_consoleOutput.setObjectName("textBrowser_consoleOutput")
        self.ConsoleLayout.addWidget(self.textBrowser_consoleOutput)
        self.TopBtnLayout.addLayout(self.ConsoleLayout)
        self.mainLayout.addLayout(self.TopBtnLayout)
        spacerItem2 = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mainLayout.addWidget(self.line)
        self.picLabel = QtWidgets.QLabel(self.centralWidget)
        self.picLabel.setMinimumSize(QtCore.QSize(0, 312))
        self.picLabel.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.picLabel.setText("")
        self.picLabel.setScaledContents(True)
        self.picLabel.setObjectName("picLabel")
        self.mainLayout.addWidget(self.picLabel)
        self.verticalLayout.addLayout(self.mainLayout)
        skeleton.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(skeleton)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1070, 22))
        self.menuBar.setObjectName("menuBar")
        skeleton.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(skeleton)
        self.mainToolBar.setObjectName("mainToolBar")
        skeleton.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(skeleton)
        self.statusBar.setObjectName("statusBar")
        skeleton.setStatusBar(self.statusBar)

        self.retranslateUi(skeleton)
        QtCore.QMetaObject.connectSlotsByName(skeleton)

    def retranslateUi(self, skeleton):
        _translate = QtCore.QCoreApplication.translate
        skeleton.setWindowTitle(_translate("skeleton", "MainWindow"))
        self.label_points.setText(_translate("skeleton", "Items on picture"))
        self.label_tech.setText(_translate("skeleton", "Reset analysis"))
        self.btn_reset.setToolTip(_translate("skeleton", "<html><head/><body><p>Reset all the selected points and calculated variables</p></body></html>"))
        self.btn_reset.setText(_translate("skeleton", "Reset"))
        self.label_Zoom.setText(_translate("skeleton", "Zoom"))
        self.btn_ZoomIn.setToolTip(_translate("skeleton", "<html><head/><body><p>Zoom into the picture</p></body></html>"))
        self.btn_ZoomIn.setText(_translate("skeleton", "Zoom In"))
        self.btn_ZoomOut.setToolTip(_translate("skeleton", "<html><head/><body><p>Zoom out from the picture</p></body></html>"))
        self.btn_ZoomOut.setText(_translate("skeleton", "Zoom Out"))
        self.label_calc.setText(_translate("skeleton", "Calculate"))
        self.btn_trackMom.setToolTip(_translate("skeleton", "<html><head/><body><p>Calculate Track momentum</p></body></html>"))
        self.btn_trackMom.setText(_translate("skeleton", "Cal Track Momemetum"))
        self.btn_optDen.setToolTip(_translate("skeleton", "<html><head/><body><p>Calculate Optical Density</p></body></html>"))
        self.btn_optDen.setText(_translate("skeleton", "Calc Optical Density"))
        self.btn_angle.setToolTip(_translate("skeleton", "<html><head/><body><p>Calculate Opening Angle</p></body></html>"))
        self.btn_angle.setText(_translate("skeleton", "Caculate Angle"))
        self.label_userSle.setText(_translate("skeleton", "User selection"))
        self.btn_openImage.setToolTip(_translate("skeleton", "<html><head/><body><p>Open Image for analysis</p></body></html>"))
        self.btn_openImage.setText(_translate("skeleton", "Open Image"))
        self.btn_placeMar.setToolTip(_translate("skeleton", "<html><head/><body><p>Place a new marker on the track</p></body></html>"))
        self.btn_placeMar.setText(_translate("skeleton", "Place Track Marker"))
        self.setDlLabel.setText(_translate("skeleton", "Set DL"))
        self.btn_drwAngle.setToolTip(_translate("skeleton", "<html><head/><body><p>Draw reference for angle</p><p><br/></p></body></html>"))
        self.btn_drwAngle.setText(_translate("skeleton", "Draw Angle Reference"))
        self.label_console.setText(_translate("skeleton", "Console"))

