# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traxis.ui'
#
# Created: Sun Oct 26 02:18:45 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_traxis(object):
    def setupUi(self, traxis):
        traxis.setObjectName("traxis")
        traxis.resize(1060, 665)
        traxis.setMaximumSize(QtCore.QSize(100000, 1000000))
        self.centralWidget = QtWidgets.QWidget(traxis)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.TopBtnLayout = QtWidgets.QHBoxLayout()
        self.TopBtnLayout.setObjectName("TopBtnLayout")
        self.PointInfo = QtWidgets.QTableWidget(self.centralWidget)
        self.PointInfo.setMinimumSize(QtCore.QSize(375, 0))
        self.PointInfo.setMaximumSize(QtCore.QSize(400, 16777192))
        self.PointInfo.setObjectName("PointInfo")
        self.PointInfo.setColumnCount(3)
        self.PointInfo.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PointInfo.setHorizontalHeaderItem(2, item)
        self.TopBtnLayout.addWidget(self.PointInfo)
        self.vLine_div2 = QtWidgets.QFrame(self.centralWidget)
        self.vLine_div2.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.vLine_div2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vLine_div2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vLine_div2.setObjectName("vLine_div2")
        self.TopBtnLayout.addWidget(self.vLine_div2)
        self.tech_calc_btnLayoy = QtWidgets.QVBoxLayout()
        self.tech_calc_btnLayoy.setObjectName("tech_calc_btnLayoy")
        self.label_tech = QtWidgets.QLabel(self.centralWidget)
        self.label_tech.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_tech.setObjectName("label_tech")
        self.tech_calc_btnLayoy.addWidget(self.label_tech)
        self.btn_reset = QtWidgets.QPushButton(self.centralWidget)
        self.btn_reset.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_reset.setObjectName("btn_reset")
        self.tech_calc_btnLayoy.addWidget(self.btn_reset)
        self.sld_zoom = QtWidgets.QSlider(self.centralWidget)
        self.sld_zoom.setEnabled(True)
        self.sld_zoom.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.sld_zoom.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sld_zoom.setAccessibleName("")
        self.sld_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.sld_zoom.setObjectName("sld_zoom")
        self.tech_calc_btnLayoy.addWidget(self.sld_zoom)
        self.label_calc = QtWidgets.QLabel(self.centralWidget)
        self.label_calc.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_calc.setObjectName("label_calc")
        self.tech_calc_btnLayoy.addWidget(self.label_calc)
        self.btn_trackMom = QtWidgets.QPushButton(self.centralWidget)
        self.btn_trackMom.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_trackMom.setObjectName("btn_trackMom")
        self.tech_calc_btnLayoy.addWidget(self.btn_trackMom)
        self.btn_optDen = QtWidgets.QPushButton(self.centralWidget)
        self.btn_optDen.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_optDen.setObjectName("btn_optDen")
        self.tech_calc_btnLayoy.addWidget(self.btn_optDen)
        self.btn_angle = QtWidgets.QPushButton(self.centralWidget)
        self.btn_angle.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_angle.setStyleSheet("")
        self.btn_angle.setObjectName("btn_angle")
        self.tech_calc_btnLayoy.addWidget(self.btn_angle)
        spacerItem = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tech_calc_btnLayoy.addItem(spacerItem)
        self.TopBtnLayout.addLayout(self.tech_calc_btnLayoy)
        self.usrSel_layout = QtWidgets.QVBoxLayout()
        self.usrSel_layout.setObjectName("usrSel_layout")
        self.label_userSle = QtWidgets.QLabel(self.centralWidget)
        self.label_userSle.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_userSle.setObjectName("label_userSle")
        self.usrSel_layout.addWidget(self.label_userSle)
        self.btn_placeMar = QtWidgets.QPushButton(self.centralWidget)
        self.btn_placeMar.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_placeMar.setObjectName("btn_placeMar")
        self.usrSel_layout.addWidget(self.btn_placeMar)
        self.dlForm = QtWidgets.QFormLayout()
        self.dlForm.setObjectName("dlForm")
        self.setDlLabel = QtWidgets.QLabel(self.centralWidget)
        self.setDlLabel.setObjectName("setDlLabel")
        self.dlForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.setDlLabel)
        self.setDlLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.setDlLineEdit.setObjectName("setDlLineEdit")
        self.dlForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.setDlLineEdit)
        self.usrSel_layout.addLayout(self.dlForm)
        self.btn_drwAngle = QtWidgets.QPushButton(self.centralWidget)
        self.btn_drwAngle.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.btn_drwAngle.setObjectName("btn_drwAngle")
        self.usrSel_layout.addWidget(self.btn_drwAngle)
        spacerItem1 = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.usrSel_layout.addItem(spacerItem1)
        self.TopBtnLayout.addLayout(self.usrSel_layout)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.TopBtnLayout.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(250, 0))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.TopBtnLayout.addLayout(self.verticalLayout_3)
        self.AllBtnLayout = QtWidgets.QHBoxLayout()
        self.AllBtnLayout.setObjectName("AllBtnLayout")
        self.TopBtnLayout.addLayout(self.AllBtnLayout)
        self.mainLayout.addLayout(self.TopBtnLayout)
        spacerItem2 = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mainLayout.addWidget(self.line)
        self.picLabel = QtWidgets.QLabel(self.centralWidget)
        self.picLabel.setMinimumSize(QtCore.QSize(0, 312))
        self.picLabel.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.picLabel.setText("")
        self.picLabel.setScaledContents(True)
        self.picLabel.setObjectName("picLabel")
        self.mainLayout.addWidget(self.picLabel)
        self.verticalLayout.addLayout(self.mainLayout)
        traxis.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(traxis)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1060, 22))
        self.menuBar.setObjectName("menuBar")
        traxis.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(traxis)
        self.mainToolBar.setObjectName("mainToolBar")
        traxis.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(traxis)
        self.statusBar.setObjectName("statusBar")
        traxis.setStatusBar(self.statusBar)

        self.retranslateUi(traxis)
        QtCore.QMetaObject.connectSlotsByName(traxis)

    def retranslateUi(self, traxis):
        _translate = QtCore.QCoreApplication.translate
        traxis.setWindowTitle(_translate("traxis", "MainWindow"))
        self.PointInfo.setToolTip(_translate("traxis", "<html><head/><body><p>Points selected on the track</p></body></html>"))
        item = self.PointInfo.verticalHeaderItem(0)
        item.setText(_translate("traxis", "New Row"))
        item = self.PointInfo.verticalHeaderItem(1)
        item.setText(_translate("traxis", "New Row"))
        item = self.PointInfo.verticalHeaderItem(2)
        item.setText(_translate("traxis", "New Row"))
        item = self.PointInfo.verticalHeaderItem(3)
        item.setText(_translate("traxis", "New Row"))
        item = self.PointInfo.verticalHeaderItem(4)
        item.setText(_translate("traxis", "New Row"))
        item = self.PointInfo.verticalHeaderItem(5)
        item.setText(_translate("traxis", "New Row"))
        item = self.PointInfo.horizontalHeaderItem(0)
        item.setText(_translate("traxis", "Point"))
        item = self.PointInfo.horizontalHeaderItem(1)
        item.setText(_translate("traxis", "X Value"))
        item = self.PointInfo.horizontalHeaderItem(2)
        item.setText(_translate("traxis", "Y Value"))
        self.label_tech.setText(_translate("traxis", "Technical buttons"))
        self.btn_reset.setToolTip(_translate("traxis", "<html><head/><body><p>Reset all the selected points and calculated variables</p></body></html>"))
        self.btn_reset.setText(_translate("traxis", "Reset"))
        self.sld_zoom.setToolTip(_translate("traxis", "<html><head/><body><p>Zoom Control</p></body></html>"))
        self.label_calc.setText(_translate("traxis", "Calculate"))
        self.btn_trackMom.setToolTip(_translate("traxis", "<html><head/><body><p>Calculate Track momentum</p></body></html>"))
        self.btn_trackMom.setText(_translate("traxis", "Cal Track Momemetum"))
        self.btn_optDen.setToolTip(_translate("traxis", "<html><head/><body><p>Calculate Optical Density</p></body></html>"))
        self.btn_optDen.setText(_translate("traxis", "Calc Optical Density"))
        self.btn_angle.setToolTip(_translate("traxis", "<html><head/><body><p>Calculate Opening Angle</p></body></html>"))
        self.btn_angle.setText(_translate("traxis", "Caculate Angle"))
        self.label_userSle.setText(_translate("traxis", "User selection"))
        self.btn_placeMar.setToolTip(_translate("traxis", "<html><head/><body><p>Place a new marker on the track</p></body></html>"))
        self.btn_placeMar.setText(_translate("traxis", "Place track marker"))
        self.setDlLabel.setText(_translate("traxis", "set DL"))
        self.btn_drwAngle.setToolTip(_translate("traxis", "<html><head/><body><p>Draw reference for angle</p><p><br/></p></body></html>"))
        self.btn_drwAngle.setText(_translate("traxis", "Draw angle ref."))
        self.label.setText(_translate("traxis", "Console"))

