# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traxis.ui'
#
# Created: Sat Oct 25 23:21:29 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_traxis(object):
    def setupUi(self, traxis):
        traxis.setObjectName("traxis")
        traxis.resize(1000, 665)
        traxis.setMaximumSize(QtCore.QSize(100000, 1000000))
        self.centralWidget = QtWidgets.QWidget(traxis)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(400, 16777192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.Zoom_2 = QtWidgets.QSlider(self.centralWidget)
        self.Zoom_2.setEnabled(True)
        self.Zoom_2.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.Zoom_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Zoom_2.setAccessibleName("")
        self.Zoom_2.setOrientation(QtCore.Qt.Horizontal)
        self.Zoom_2.setObjectName("Zoom_2")
        self.verticalLayout_4.addWidget(self.Zoom_2)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        spacerItem = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.Zoom = QtWidgets.QSlider(self.centralWidget)
        self.Zoom.setEnabled(True)
        self.Zoom.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.Zoom.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Zoom.setOrientation(QtCore.Qt.Horizontal)
        self.Zoom.setObjectName("Zoom")
        self.verticalLayout_5.addWidget(self.Zoom)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(16777215, 16777192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label1 = QtWidgets.QLabel(self.centralWidget)
        self.label1.setMinimumSize(QtCore.QSize(0, 312))
        self.label1.setMaximumSize(QtCore.QSize(16777215, 16777192))
        self.label1.setText("")
        self.label1.setScaledContents(True)
        self.label1.setObjectName("label1")
        self.verticalLayout_2.addWidget(self.label1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        traxis.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(traxis)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName("menuBar")
        traxis.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(traxis)
        self.mainToolBar.setObjectName("mainToolBar")
        traxis.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(traxis)
        self.statusBar.setObjectName("statusBar")
        traxis.setStatusBar(self.statusBar)

        self.retranslateUi(traxis)
        QtCore.QMetaObject.connectSlotsByName(traxis)

    def retranslateUi(self, traxis):
        _translate = QtCore.QCoreApplication.translate
        traxis.setWindowTitle(_translate("traxis", "MainWindow"))
        self.tableWidget.setToolTip(_translate("traxis", "<html><head/><body><p>Points selected on the track</p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("traxis", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("traxis", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("traxis", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("traxis", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("traxis", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("traxis", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("traxis", "Point"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("traxis", "X Value"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("traxis", "Y Value"))
        self.label_3.setText(_translate("traxis", "Technical buttons"))
        self.pushButton_4.setToolTip(_translate("traxis", "<html><head/><body><p>Reset all the selected points and calculated variables</p></body></html>"))
        self.pushButton_4.setText(_translate("traxis", "Reset"))
        self.Zoom_2.setToolTip(_translate("traxis", "<html><head/><body><p>Zoom Control</p></body></html>"))
        self.label_2.setText(_translate("traxis", "Calculate"))
        self.pushButton_3.setToolTip(_translate("traxis", "<html><head/><body><p>Calculate Track momentum</p></body></html>"))
        self.pushButton_3.setText(_translate("traxis", "Cal Track Momemetum"))
        self.pushButton_5.setToolTip(_translate("traxis", "<html><head/><body><p>Calculate Optical Density</p></body></html>"))
        self.pushButton_5.setText(_translate("traxis", "Calc optical density"))
        self.pushButton_6.setToolTip(_translate("traxis", "<html><head/><body><p>Calculate Opening Angle</p></body></html>"))
        self.pushButton_6.setText(_translate("traxis", "Caculate Angle"))
        self.label_4.setText(_translate("traxis", "User selection"))
        self.pushButton.setToolTip(_translate("traxis", "<html><head/><body><p>Place a new marker on the track</p></body></html>"))
        self.pushButton.setText(_translate("traxis", "Place track marker"))
        self.Zoom.setToolTip(_translate("traxis", "<html><head/><body><p>dL input</p></body></html>"))
        self.pushButton_2.setToolTip(_translate("traxis", "<html><head/><body><p>Draw reference for angle</p><p><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("traxis", "Draw angle ref."))

